## One Dimensional Array

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)   # by default it will give int64 if integer

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


# Two dimensional Array

In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print()
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

<class 'numpy.ndarray'>
2
(3, 4)
12
int64


In [9]:
arr=np.array([[1,2,3,4]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2
(1, 4)
4
int64


# Three Dimensional Array(3-D array)

In [11]:
arr=np.array([[[1,2,3,4]]])
print(arr)
print()
print(type(arr))
print(arr.ndim)
print(arr.shape)  # block,rows,column
print(arr.size)
print(arr.dtype)

[[[1 2 3 4]]]

<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64


In [27]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4]],[[9,10,11,12],[13,14,15,16],[1,2,3,4]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 1  2  3  4]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [ 1  2  3  4]]]
<class 'numpy.ndarray'>
3
(2, 3, 4)
24
int64


In [29]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
3
(3, 3, 3)
27
int64


# Iteration in Array

In [30]:
 # Direct Iteration

arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [37]:
# indirect Iteration
arr=np.array([1,2,3,4,5])
for i in range(len(arr)):
    print(i," ",arr[i])

0   1
1   2
2   3
3   4
4   5


In [35]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [36]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


In [48]:
# Iteration for 3-D array
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print('\n')

print()
for i in arr:
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]



[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [49]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print("\n")
for i in arr:
    for j in i:
        print(j)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [50]:
 
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print("\n")
for i in arr:
    for j in i:
        for k in j:
            print(k)
        

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [51]:
# nd.iter()
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
for i in np.nditer(arr):
    print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [52]:
# nd.enumerate
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
for i in np.ndenumerate(arr):
    print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(4))
((0, 1, 1), np.int64(5))
((0, 1, 2), np.int64(6))
((0, 2, 0), np.int64(7))
((0, 2, 1), np.int64(8))
((0, 2, 2), np.int64(9))
((1, 0, 0), np.int64(10))
((1, 0, 1), np.int64(11))
((1, 0, 2), np.int64(12))
((1, 1, 0), np.int64(13))
((1, 1, 1), np.int64(14))
((1, 1, 2), np.int64(15))
((1, 2, 0), np.int64(16))
((1, 2, 1), np.int64(17))
((1, 2, 2), np.int64(18))
((2, 0, 0), np.int64(19))
((2, 0, 1), np.int64(20))
((2, 0, 2), np.int64(21))
((2, 1, 0), np.int64(22))
((2, 1, 1), np.int64(23))
((2, 1, 2), np.int64(24))
((2, 2, 0), np.int64(25))
((2, 2, 1), np.int64(26))
((2, 2, 2), np.int64(27))
