In [7]:
import numpy as np

## evenly spaced array

#### np.linspace(start,end,[numbers])
#### BY default number value-50


In [10]:

arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
arr=np.linspace(0,10)
print(arr)    # by default 50  numbers 
print(len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
50


## Random function:-

#### randint:
#### random.randint( start , stop,shape)

In [13]:
# Array with random number:
# randint:
# random.randint( start , stop,shape)
arr=np.random.randint(20,30,(2,2,5))
print(arr)

[[[25 26 25 22 29]
  [26 22 25 29 28]]

 [[22 22 21 29 26]
  [29 22 25 26 22]]]


In [18]:
# by default take only one value in shape
arr=np.random.randint(20,30)
print(arr)

28


In [17]:
arr=np.random.randint(20,30,5)
print(arr)

[28 25 28 25 22]


#### np.random.rand(shape)
#### takes values in between 0 to 1 only 
#### where o is inclusive and 1 is exclusive 

In [19]:
arr=np.random.rand(2,2,5)
print(arr)

[[[0.37581791 0.91766921 0.79632655 0.51270309 0.43888201]
  [0.64876043 0.41990752 0.00830871 0.74499243 0.98210647]]

 [[0.63927977 0.54155636 0.47427289 0.09679027 0.00971347]
  [0.20338174 0.60083687 0.23299502 0.80075579 0.7635187 ]]]


#### np.random.randn()
#### Takes nearest value to 0 in  both negative and positive integer

In [20]:
arr=np.random.randn(4,6)
print(arr)

[[-0.860867   -2.89141177  0.497483   -0.66813785  1.93504436  0.53296545]
 [ 0.07741159 -0.84919434  1.26178421  1.65464698 -0.48957394 -1.23649592]
 [-0.34065652 -0.36752099 -0.70220601 -0.93580108  0.65062931  1.21476667]
 [-0.26000343 -0.70950302 -0.45065518 -0.795448   -0.365533   -1.10045332]]
