In [1]:
import numpy as np

# arange function:-

In [4]:
# arange function
arr=np.arange(1,10)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[::])
print(arr[::-1])
print(arr[1::3])

[1 2 3 4 5 6 7 8 9]
1
9
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[2 5 8]


In [18]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print("\n")
print(arr[1::2])
print("\n")
print(arr[::-1])
print(arr[0][1][0])
print(arr[2][1][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]]


[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
4
23


# Special Filled Arrays   
By default gives float value
#### 1) np.zeros()
#### 2) np.ones()
#### 3) np.full()
#### 4) np.eye()

### np.zeros(shape)

In [12]:
# np.zeros()
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [13]:
arr=np.zeros(4,dtype="int")
print(arr)

[0 0 0 0]


In [14]:
arr= np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
arr=np.zeros(((4,4,4)))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### np.ones(shape)

In [19]:
arr=np.ones(1)
print(arr)

[1.]


In [21]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [24]:
arr=np.ones((2,2,2))
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### np.full((shape),constant)

In [25]:
# full 
arr=np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### np.eye(shape)  
used for diagonal

In [26]:
# eye
arr=np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [27]:
arr=np.eye(4,4)
print(arr[::-1])

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [29]:
arr=np.array([123,127,126],dtype="int8")
print(arr)

[123 127 126]


 arr=np.array([128,127,126],dtype="int8") 
 
 print(arr)     # (will give error)     # Python integer 128 out of bounds for int8 